name: intelligent-tests-pr
on:
  workflow_dispatch:
  pull_request:
    types: [labeled, opened, synchronize, reopened, review_requested]

permissions:
  actions: read
  pull-requests: write

jobs:
  display_test_results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - run_tests

    steps:
      - name: Download all test results
        uses: actions/download-artifact@v3

      - name: Combined Test Results
        run: |
          find . -name "test_results_*.txt" -exec cat {} + > combined_test_results.txt
          echo "Test results summary:"
          cat combined_test_results.txt

      - name: New Failures Introduced
        run: |
          find . -name "new_failures_*.txt" -exec cat {} + > combined_failures.txt
          if [ -s combined_failures.txt ]
          then
              echo "This PR introduces the following new failing tests:"
              cat combined_failures.txt
          else
              echo "This PR does not introduce any new test failures! Yippee!"
          fi

  run_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                  11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
                  21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
                  31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
                  41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
                  51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
                  61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
                  71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
                  81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
                  91, 92, 93, 94, 95, 96, 97, 98, 99, 100,
                  101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                  111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
                  121, 122, 123, 124, 125, 126, 127, 128 ]

    steps:
      - name: Checkout Ivy 🛎
        uses: actions/checkout@v3
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 100

      - name: Determine and Run Tests
        id: tests
        run: |
          git clone -b master${{ matrix.branch }} https://github.com/unifyai/Mapping.git --depth 200
          pip install pydriller GitPython
          python ivy/run_tests_CLI/clone-mapping.py
          cp Mapping/tests.pbz2 ivy/
          cd ivy
          mkdir .ivy
          touch .ivy/key.pem
          echo -n ${{ secrets.USER_API_KEY }} > .ivy/key.pem
          python determine_tests.py ${{ matrix.branch }} pr
          set -o pipefail
          python run_tests_pr.py new_failures_${{ matrix.branch }}.txt | tee test_results_${{ matrix.branch }}.txt
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test_results_${{ matrix.branch }}
          path: ivy/test_results_${{ matrix.branch }}.txt

      - name: Upload New Failures
        uses: actions/upload-artifact@v3
        with:
          name: new_failures_${{ matrix.branch }}
          path: ivy/new_failures_${{ matrix.branch }}.txt

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
