name: Trigger lint format

on:
  pull_request:
    types: [opened, edited, synchronize, labeled, unlabeled, ready_for_review, reopened]

permissions:
  contents: write

jobs:
  fix-linting:
    name: PR Lint Bot
    uses: unifyai/workflows/.github/workflows/pr-lint-bot.yml@automatic-lint-pr
    secrets: inherit
