name: Pre-release Testing Workflow
on:
  workflow_dispatch:

permissions:
  actions: read
jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: [ivy.txt, torch.txt]
    steps:
      - name: Checkout Ivy 🛎
        uses: actions/checkout@v3
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 1

      - name: Get Job URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Run Tests
        run: |
          pip3 install pymongo
          cd ivy
          mkdir .ivy
          touch .ivy/key.pem
          echo -n ${{ secrets.USER_API_KEY }} > .ivy/key.pem
          python run_tests_CLI/setup_priority_tests.py priority_tests/${{ matrix.file }}
          python run_tests.py ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD }} ${{ secrets.MONGODB_PASSWORD }} 'false' 'false' ${{ github.run_id }} 'true' ${{ steps.jobs.outputs.html_url }}
